# Generated by Django 4.2.1 on 2023-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
