# Generated by Django 4.2.1 on 2023-05-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_problemcomment_owner_and_more'),
        ('article', '0003_alter_article_owner_alter_article_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
