# Generated by Django 4.2.1 on 2023-05-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_alter_article_owner_alter_article_reputation'),
        ('problem', '0004_alter_problem_options_problem_created_time_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(null=True, to='article.article'),
        ),
        migrations.AlterField(
            model_name='category',
            name='problems',
            field=models.ManyToManyField(null=True, to='problem.problem'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
