# Generated by Django 4.2.1 on 2023-05-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_owner_alter_article_reputation'),
        ('problem', '0004_alter_problem_options_problem_created_time_and_more'),
        ('main', '0002_alter_articlecomment_owner_alter_category_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(default=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
        migrations.AlterField(
            model_name='category',
            name='problems',
            field=models.ManyToManyField(default=django.db.models.deletion.SET_NULL, to='problem.problem'),
        ),
    ]
