# Generated by Django 4.2.1 on 2023-05-21 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_alter_problem_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='problem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
