# Generated by Django 4.2.1 on 2023-06-12 12:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
